version: '3.8'

services:
  backend:
    build: ./custom-clearance-backend
    restart: unless-stopped
    networks:
      - app

  frontend:
    build: ./cutom-clearance-frontend
    container_name: clearance-frontend
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app
      - web

networks:
  app:
  web:
    external: true
